version: 2
jobs:
  build:
    working_directory: /app/user
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: npm install
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          command: npm install express-session co mongodb csrf ejs jquery cookie fs-extra aws-sdk
      - run:
          command: npm install --save-dev jest
      - run:
          command: npm test
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               chmod 755 ./.circleci/setup-heroku.sh
              ./.circleci/setup-heroku.sh
              echo --- git push
              git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/
              git push heroku master --force
            fi
