version: 2
jobs:
  deploy:
    docker:
      - image: node:6.10.0
    steps:
      - checkout
      - run:
          name: git init
          command: git init
      - run:
          name: heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
