version: 2
jobs:
  build:
    working_directory: /app/user
    docker:
      - image: atsnngs/heroku-nodejs-ci:latest
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: npm install
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          command: npm test
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pwd
              ls -al
              chmod 755 ./.circleci/setup-heroku.sh
              ./.circleci/setup-heroku.sh
              git pull heroku master
              $git config --global user.email shigeru@yokochi.jp
              $git config --global user.name shigeru yokochi
              git push heroku master
            fi
