version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:6.10.0

    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
            fi


